### ISSUE TITLE
es2015 deprecated, use babel-preset-env instead

### ISSUE THREAD

**Issue by sergiowobiz** [wyzantinc/vue-radial-progress#10]
Installing the plugin I got this message, it's related to the fact that babel-preset-es20XX have been replaced with babel-preset-env:
"npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!"

**Comment by justice47** [comment]
That problem should be fixed then #14 PR will be merged

**Comment by mca312** [comment]
resolved in latest version
