### ISSUE TITLE
Module build failed: Error: Cannot find module 'babel-plugin-transform-runtime'

### ISSUE THREAD

**Issue by jcjollant** [wyzantinc/vue-radial-progress#12]
I cannot build my vue app with this error.
It's also suggesting to use "@babel/transform-runtime" instead

**Comment by alialsabe** [comment]
I have the same issue. I tried playing with babel but couldn't fix it.

**Comment by chrizz1001** [comment]
You can npm install in node_modules sub directory for this module, then it works. Though, this does not help while in deploying process... It will break with error

**Comment by RoraxHan** [comment]
Please install library from the github, that will fix the problem.

**Comment by mca312** [comment]
resolved in latest version
