### ISSUE TITLE
SSR / NUXT

### ISSUE THREAD

**Issue by furyscript** [wyzantinc/vue-radial-progress#13]
Can you add compatibility with nuxt/ssr?

**Comment by furyscript** [comment]
@jrenton

**Comment by DingoDongBlueBalls** [comment]
Found a workaround for this...

1. Copy-paste the contents of RadialProgressBar.vue from here: https://github.com/wyzant-dev/vue-radial-progress/blob/master/src/RadialProgressBar.vue
2. Create a new component in your nuxt project and paste it in there.
3. Import the component to the page(s) where you wanna use them.
4. call the component within <no-ssr></no-ssr> tags inside the template.(wont work without this...)

**Comment by dark-reiser** [comment]
> Found a workaround for this...
> 
>     1. Copy-paste the contents of RadialProgressBar.vue from here: https://github.com/wyzant-dev/vue-radial-progress/blob/master/src/RadialProgressBar.vue
> 
>     2. Create a new component in your nuxt project and paste it in there.
> 
>     3. Import the component to the page(s) where you wanna use them.
> 
>     4. call the component within no-ssr tags inside the template.(wont work without this...)

thanks dude, it's work for ssr!, hope the creator update the repo

**Comment by mca312** [comment]
Sorry, I'm unfamiliar with what needs to be done for SSR.  Please open a PR with the necessary changes.

**Comment by pana1990** [comment]
@jrenton can we send pr to include this fix in docs?

it is usefull to nuxt developers, i hold on by your reply.

Regards.

**Comment by mca312** [comment]
@pana1990  you can open a PR for us to review.  As I mentioned, I am unfamiliar with NUXT and what needs to be done

**Comment by pana1990** [comment]
@mca312 of course :)
