### ISSUE TITLE
support for drop shadow

### ISSUE THREAD

**Issue by marabesi** [wyzantinc/vue-radial-progress#21]
I just came across a scenario where I would like to add a drop shadow to the svg circle element.
Something like this one https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feDropShadow.
The problem is that the component has a single slot to render child components, something like:

```html
    <radial-progress-bar
      class="loader"
    >
       <p>child1</p>
       <span>child2</span>
    </radial-progress-bar>
```

Which places the child1 and child 2 above the svg element. 

A reasonable approach to that would be to allow a second slot to pass in defs, something like:

```html
    <svg class="radial-progress-bar"
         :width="diameter"
         :height="diameter"
         version="1.1"
         xmlns="http://www.w3.org/2000/svg">

      <slot name="defs" />

      <defs>
          ....
      </defs>
</svg>
```

Is there another way around that?

**Comment by mca312** [comment]
Sorry, I'm unfamiliar with this.  Is there a current issue with the plugin?  I'm going to close this but please reopen if there is an issue.
