### ISSUE TITLE
when iphone upgrade to the latest version 13.X.X,the progress bar animation does not appear

### ISSUE THREAD

**Issue by gegelulu** [wyzantinc/vue-radial-progress#24]
if the phone not upgrade 13.X.X,everything is OK .After upgraded 13.x.x,only the progress bar not appear.

**Comment by mca312** [comment]
Can I get other information or a site I can look at?  I've tested locally using the xcode simulator and am not seeing a problem.

**Comment by mca312** [comment]
@gegelulu please reopen with more information is this is still occurring.  I cannot reproduce, butI am using xcode simulator as I do not have an iphone
