### ISSUE TITLE
No longer works for the new preset

### ISSUE THREAD

**Issue by intijk** [wyzantinc/vue-radial-progress#8]
When building with new babel, it gives:

`Module build failed: Error: Couldn't find preset "es2015" relative to directory "......`

**Comment by creazy231** [comment]
same problem here :( any workaround or fix?

**Comment by creazy231** [comment]
**Workaround:**
1. Create a new component inside your project
2. Copy the content of RadialProgressBar.vue to your new created component or just download the RadialProgressBar.vue file [https://github.com/wyzant-dev/vue-radial-progress/blob/master/src/RadialProgressBar.vue](url)
3. Import the component like a normal component ¯\_(ツ)_/¯
4. Use the radial progress bar as described in the documentation here

**Comment by einnar82** [comment]
check the node_modules directory and look for vue-radial-progress 

then change the .babelrc config to

`{
    "presets": ['env']
}`


your machine must install the babel-preset-env :)

**Comment by mca312** [comment]
Babel has been updated. Please open a new issue if the problem occurs
