### ISSUE TITLE
Animatespeed 0 causes radial gradient errors

### ISSUE THREAD

**Issue by robbeman** [wyzantinc/vue-radial-progress#9]
The console fills up with `Error: <radialGradient> attribute fx: Expected length, "NaN".` when the animation speed is set to 0. Havent gone through a thorough search why, but I can tell that `gradient.fx` and `gradient.fy` are NaN.

![image](https://user-images.githubusercontent.com/3245659/34161131-d7164f66-e4cf-11e7-932d-8e0fa2a26bd1.png)

This is because `this.currentAngle` is also NaN and passed to `getPointOfCircle`. (And `animateSlice` is set to Infinity.)

Setting the animation speed to 1 works, though.

**Comment by Cholowao** [comment]
anybody

**Comment by justice47** [comment]
Please reproduce error in any online editor.
I cant reproduce it, though. Here are the codesandbox example with `:animateSpeed="0"` - https://codesandbox.io/embed/vue-template-fxtij

**Comment by mubaidr** [comment]
^ @justice47 your provided demo also produces errors. Please check the `console`

**Comment by gegelulu** [comment]
add 
if (this.totalSteps === 0) {
        return 0
    }  
to 
circleSlice () {
    if (this.totalSteps === 0) {
        return 0
    }
    return 2 * Math.PI / this.totalSteps
  }
bcz Math.sin(Inf) = NaN
